skus:
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 192
  perishability_days: 14
  safety_stock_days: 1
  sku: FOODS_2_019
  unit_cost: 1.78
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 210
  perishability_days: 7
  safety_stock_days: 1
  sku: FOODS_2_197
  unit_cost: 1.78
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 213
  perishability_days: 14
  safety_stock_days: 1
  sku: FOODS_2_276
  unit_cost: 1.78
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 198
  perishability_days: 14
  safety_stock_days: 1
  sku: FOODS_2_347
  unit_cost: 1.11
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 213
  perishability_days: 7
  safety_stock_days: 1
  sku: FOODS_3_064
  unit_cost: 0.63
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 159
  perishability_days: 7
  safety_stock_days: 1
  sku: FOODS_3_080
  unit_cost: 0.88
- category: FOODS
  max_budget_per_order: 643
  max_shelf_capacity: 1797
  perishability_days: 14
  safety_stock_days: 1
  sku: FOODS_3_090
  unit_cost: 0.76
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 156
  perishability_days: 10
  safety_stock_days: 1
  sku: FOODS_3_099
  unit_cost: 1.37
- category: FOODS
  max_budget_per_order: 1394
  max_shelf_capacity: 615
  perishability_days: 14
  safety_stock_days: 1
  sku: FOODS_3_120
  unit_cost: 2.74
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 270
  perishability_days: 14
  safety_stock_days: 1
  sku: FOODS_3_202
  unit_cost: 2.38
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 441
  perishability_days: 14
  safety_stock_days: 1
  sku: FOODS_3_252
  unit_cost: 0.84
- category: FOODS
  max_budget_per_order: 508
  max_shelf_capacity: 357
  perishability_days: 14
  safety_stock_days: 1
  sku: FOODS_3_282
  unit_cost: 1.38
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 234
  perishability_days: 7
  safety_stock_days: 1
  sku: FOODS_3_295
  unit_cost: 0.45
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 663
  perishability_days: 14
  safety_stock_days: 1
  sku: FOODS_3_318
  unit_cost: 0.73
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 267
  perishability_days: 10
  safety_stock_days: 1
  sku: FOODS_3_319
  unit_cost: 0.55
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 273
  perishability_days: 7
  safety_stock_days: 1
  sku: FOODS_3_491
  unit_cost: 0.76
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 360
  perishability_days: 10
  safety_stock_days: 1
  sku: FOODS_3_501
  unit_cost: 0.45
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 363
  perishability_days: 10
  safety_stock_days: 1
  sku: FOODS_3_541
  unit_cost: 0.55
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 189
  perishability_days: 10
  safety_stock_days: 1
  sku: FOODS_3_555
  unit_cost: 0.88
- category: FOODS
  max_budget_per_order: 510
  max_shelf_capacity: 399
  perishability_days: 10
  safety_stock_days: 1
  sku: FOODS_3_586
  unit_cost: 0.88
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 414
  perishability_days: 7
  safety_stock_days: 1
  sku: FOODS_3_587
  unit_cost: 1.41
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 267
  perishability_days: 7
  safety_stock_days: 1
  sku: FOODS_3_607
  unit_cost: 1.24
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 372
  perishability_days: 10
  safety_stock_days: 1
  sku: FOODS_3_635
  unit_cost: 0.55
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 822
  perishability_days: 10
  safety_stock_days: 1
  sku: FOODS_3_681
  unit_cost: 0.61
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 126
  perishability_days: 7
  safety_stock_days: 1
  sku: FOODS_3_694
  unit_cost: 0.88
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 279
  perishability_days: 7
  safety_stock_days: 1
  sku: FOODS_3_714
  unit_cost: 0.84
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 285
  perishability_days: 7
  safety_stock_days: 1
  sku: FOODS_3_723
  unit_cost: 0.76
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 270
  perishability_days: 14
  safety_stock_days: 1
  sku: FOODS_3_741
  unit_cost: 0.73
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 1944
  perishability_days: 14
  safety_stock_days: 1
  sku: FOODS_3_785
  unit_cost: 1.73
- category: FOODS
  max_budget_per_order: 500
  max_shelf_capacity: 618
  perishability_days: 14
  safety_stock_days: 1
  sku: FOODS_3_808
  unit_cost: 0.55
